### ISSUE TITLE
redeploy comba & get the same error !!

### ISSUE THREAD

**Issue by todokku** [GetStream/comba#10]
redeploy & get the same error :

I've also done cellphone authentication for the Mailgun plugin before

Create app

App creation failed. Please ensure you have valid values in the above form fields.
Configure environment

There was an issue setting up your app environment.

That add-on plan is only available to select users.

I've also done cellphone authentication for the Mailgun addon before

**Comment by mahboubii** [comment]
@nparsons08 looks like an issue with `stream:chat-trial` plan on Heroku

**Comment by nparsons08** [comment]
Hey @todokku, this isn't quite ready for production deployment but should be by the end of the month. Will keep you posted!

**Comment by krsnaa** [comment]
@nparsons08 @mahboubii - any updates?
The error still occurs when deploying to Heroku.

Any workarounds around manually creating an account with Stream and entering credentials?
