### ISSUE TITLE
error on deplot to heroku

### ISSUE THREAD

**Issue by todokku** [GetStream/comba#9]
im getting error on deploy to heroku ,
error : "Couldn't find either the add-on service or the add-on plan of "rediscloud:30MB"."
https://poshtiban.herokuapp.com/
error : 

error | "Missing or incorrect auth credentials."
-- | --

please check againg app.json app to fix errors ,
finest regards

**Comment by mahboubii** [comment]
@todokku should be fixed

**Comment by todokku** [comment]
redeploy & get the same error :

I've also done cellphone authentication for the Mailgun plugin before

 Create app

App creation failed. Please ensure you have valid values in the above form fields.
Configure environment

There was an issue setting up your app environment.

    That add-on plan is only available to select users.

I've also done cellphone authentication for the Mailgun plugin before
